### ISSUE TITLE
Facebook Share Issue

### ISSUE THREAD

**Issue by tuonela** [dynamodan/wordpressigniter#8]
On our WordPressIgniter site, we are having trouble sharing codeigniter generated pages on Facebook. The image, description, title, and url don't work. We have set the open graph tags, but because those pages throw a 404 error, facebook will not scrape them. We have these settings checked:

Trigger with [wordpressigniter] shortcode in posts, too.
Divert 404s to WordPressIgniter
CodeIgniter grabs all SEO urls (use with caution!!)
Use CodeIgniter's native index.php to generate constants (i.e. APPPATH, BASEPATH)

Without any of them, our codeigniter integration does not work. Our development site is password protected, but if you would like to start an email conversation, I could send you that information.

**Comment by dynamodan** [comment]
I'll look into the issue today.

Dan

**Comment by tuonela** [comment]
Great! Thank you.

**Comment by dynamodan** [comment]
This is fixed now, please update by checking out from here or getting version 1.4 from the WordPress plugin repository.

The problem was that WordPress was throwing 404's for any url that represented a CodeIgniter path that was different than the exact url that matched the WordPress page. For example, if you had a URL like this, and it triggered CodeIgniter by matching a WordPress page:

http://example.com/codeigniter

But you also had a path like this that triggered CodeIgniter:

http://example.com/codeigniter/somefunction

Then it would throw a 404 because it's not found in WordPress' scheme of things.  I suspect that's what you're having happen in your pages that facebook isn't honoring.

But now, any page that triggers CodeIgniter content will throw a 200 status code by default. Then, if you have a CodeIgniter catchall page that you intend to use to serve up a "CodeIgniter 404 Not Found" error, here's what to do.  In the CodeIgniter function (mine, for example is main/catchall), do this:

<code>
function catchall() {
    global $CI_STATUS;
    $CI_STATUS = 404;
    ...
}
</code>

Or, you can set the $CI_STATUS global variable to whatever you want, such as a 403 unauthorized if you pleased, for pages behind a special login if you needed.

**Comment by tuonela** [comment]
Awesome! That took care of the issue. Thank you for the quick response.
